- itn-installer.sh
> Update rusk wallet and add extra output

- README.md
> Added documentation to the README

- itn-installer.sh
- services/logrotate.conf
* Add logrotate conf
* Change packer url to point to main branch
The packer url should point to release only in the release branch
> Add logrotate

- README.md
- itn-installer.sh
* Change dusk binary with https://github.com/dusk-network/dusk-blockchain/commit/62e98c9642acfa86bbe2b6cf759aac0d4b6648b5
* Change installer script to stop running services during the update
* Add guide to run the unreleased installer in README.md
> Speed up block time

- README.md
- itn-installer.sh
* Added documentation to the README by @HDauven in https://github.com/dusk-network/itn-installer/pull/9
* Change consensus participation check docs by @HDauven in https://github.com/dusk-network/itn-installer/pull/10
* Add logrotate by @herr-seppia in https://github.com/dusk-network/itn-installer/pull/11
* Speed up block time by @herr-seppia in https://github.com/dusk-network/itn-installer/pull/12
* Fallback listen address to public address by @justmvg in https://github.com/dusk-network/itn-installer/pull/13
* Fix logrotate by @herr-seppia in https://github.com/dusk-network/itn-installer/pull/15
* Prompt for setting consensus keys password by @justmvg in https://github.com/dusk-network/itn-installer/pull/14
* Consensus pwd setup by @herr-seppia in …
> Release 0.0.4

- itn-installer.sh
- Update dusk binary to v0.6.1
- Update itn-installer.sh to use rusk-wallet v0.14.0
> Update node to support transaction history

- itn-installer.sh
See also:
- https://github.com/dusk-network/rusk/pull/1483
- https://github.com/dusk-network/rusk/pull/1481
- https://github.com/dusk-network/rusk/pull/1465
- https://github.com/dusk-network/rusk/pull/1454
> Upgrade rusk binary

- README.md
- bin/ruskquery
- bin/setup_consensus_pwd.sh
- conf/rusk.toml
- itn-installer.sh
- services/rusk.service
- Updates README
- Fixes bug where special characters are not picked up when setting the consensus password
- Updates the Rusk configuration to reduce bandwidth usage
- Removes the state snapshot
- Forces the wallet config
- Removes unused after in the Rusk service
- Update to the latest Rusk binary
- Add script to query for block height
> Small fixes

- bin/download_state.sh
Fix download_state when a vaild state is provided through arg
> Fix download_state.sh

- conf/rusk.toml
Add migration_height=438000
The ETA for that block is 15/05/2024 10:00 +01:00
> Add migration height

- README.md
- bin/ruskquery
- itn-installer.sh
> ITN installer version

- README.md
- bin/ruskreset
- itn-installer.sh
- Introduces `ruskreset` command.
- Instead of assuming the user is `root`, use the `~` instead.
> Add ruskreset

- node-installer.sh
> Add distro and arch check

- node-installer.sh
> Check for UFW, allow SSH and enable UFW rules

- README.md
- conf/rusk.toml
- node-installer.sh
- services/rusk.service
Resolves #75
Note that the values used for the networks are placeholders until an actual new release of the installer takes place.
> Add network selection & configuration: testnet, devnet, mainnet

- README.md
- conf/rusk.toml
- node-installer.sh
> Release 0.3.0

- README.md
- bin/ruskquery
- node-installer.sh
- Fix ruskquery block height retrieval
- Update the rusk-wallet binary with fixes for Moonlight transaction, default gas price setting and more
> Release 0.3.1

- README.md
- bin/ruskquery
- conf/dusk.conf
- conf/rusk.toml
- node-installer.sh
This release contains:
- A fix so the installer recognizes Debian
- Removes unnecessary use of sudo
- Adds mempool configuration options
- Updated version of the Rusk binary with various performance improvements and bug fixes
> Release 0.3.2

- bin/ruskreset
`ruskreset`will  now also delete the archive folder if it exists.
> Add archive deletion to ruskreset

- README.md
> Update README with OS and env support details

- README.md
- bin/ruskquery
- node-installer.sh
Hotfix for the missing ports in the mainnet bootstrapper IPs
> Release 0.5.1

- README.md
- bin/detect_ips.sh
- bin/ruskreset
- node-installer.sh
Resolves #124 #122 #89
This PR:
- Changes download URLs to use the latest release for README download URLs
- Sets the prover URL based on the targeted network
- Adds more documentation on users, groups and firewalls
- Allows non-root users to install the script
- Removes use of UFW
- Fix IP detection on Hetzner
> Small improvements

- README.md
- bin/download_state.sh
- bin/ruskquery
- node-installer.sh
- Make `download_state` mainnet only
- Add table of content to the README
- Update Rusk version & mainnet variables
> Release 0.5.3

- conf/testnet.toml
- node-installer.sh
> Update nocturne config

- node-installer.sh
See also https://github.com/dusk-network/rusk/issues/3507
> Remove verifier keys download

- bin/ruskquery
- node-installer.sh
Changes:
- Update Rusk to v1.3.0 for all networks #156
- Update Rusk Wallet to v0.2.0 for all networks #156
- Update Nocturne configuration #156
- Simplify and fix IP detection #157
- Modularize OS support #152
> Update to release 0.5.7
